vim.keymap.set("n", "<leader>L", "<Cmd>Lazy<CR>", { desc = 'Lazy: Open plugin manager' })

vim.keymap.set("n", "<leader>q", "<Cmd>qa<CR>", { desc = "Quit all windows" })
vim.keymap.set("n", "<C-q>", "<Cmd>qa<CR>", { desc = "Quit all windows" })

vim.keymap.set("n", "<leader>pp", function () vim.notify(vim.fn.expand('%:.')) end, { desc = "Print (File) Path" })

vim.keymap.set("n", "<leader>bb", "<Cmd>b#<CR>", { desc = "Buffer: Switch to previous" })
vim.keymap.set("n", "<leader>bd", "<Cmd>Bdelete<CR>", { desc = "Buffer: Delete current buffer" })
vim.keymap.set("n", "<leader>bn", "<Cmd>enew<CR>", { desc = "Buffer: Create new empty buffer" })
vim.keymap.set('n', '<leader>br', '<Cmd>e!<CR>', { desc = "Buffer: Reload file from disk" })
vim.keymap.set('n', '<leader>bw', '<Cmd>w<CR>', { desc = "Buffer: Save to file" })
vim.keymap.set('n', '<C-s>', '<Cmd>w<CR>', { desc = "Save current file" })
vim.keymap.set('n', '<leader>!', '<Cmd>e!<CR>', { desc = "Buffer: Discard changes and reload" })

vim.keymap.set("n", "<leader>wd", "<Cmd>close<CR>", { desc = "Window: Close current" })
vim.keymap.set("n", "<leader>wv", "<Cmd>vsplit<CR>", { desc = "Window: Split vertically" })
vim.keymap.set("n", "<leader>wh", "<Cmd>split<CR>", { desc = "Window: Split horizontally" })

vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Window: Navigate to left pane" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Window: Navigate to lower pane" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Window: Navigate to upper pane" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Window: Navigate to right pane" })
vim.keymap.set("n", "<C-Up>", "<Cmd>resize +2<CR>", { desc = "Window: Increase height" })
vim.keymap.set("n", "<C-Down>", "<Cmd>resize -2<CR>", { desc = "Window: Decrease height" })
vim.keymap.set("n", "<C-Left>", "<Cmd>vertical resize -2<CR>", { desc = "Window: Decrease width" })
vim.keymap.set("n", "<C-Right>", "<Cmd>vertical resize +2<CR>", { desc = "Window: Increase width" })

vim.keymap.set("n", "<M-j>", "<Cmd>execute 'move .+' . v:count1<CR>", { desc = "Move current line(s) down" })
vim.keymap.set("n", "<M-k>", "<Cmd>execute 'move .-' . (v:count1 + 1)<CR>", { desc = "Move current line(s) up" })
vim.keymap.set("v", "<M-j>", ":m '>+1<CR>gv=gv", { desc = "Move selected line(s) down", silent = true })
vim.keymap.set("v", "<M-k>", ":m '<-2<CR>gv=gv", { desc = "Move selected line(s) up", silent = true })

vim.keymap.set({ 'n', 'v' }, 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, desc = "Navigate screen lines (wrap-aware)" })
vim.keymap.set({ 'n', 'v' }, 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, desc = "Navigate screen lines (wrap-aware)" })
vim.keymap.set("n", "<M-h>", "10zh", { desc = "Horizontal scroll: View left (10 cols)" })
vim.keymap.set("n", "<M-l>", "10zl", { desc = "Horizontal scroll: View right (10 cols)" })
vim.keymap.set("n", "<M-H>", "zH", { desc = "Horizontal scroll: View left (half screen)" })
vim.keymap.set("n", "<M-L>", "zL", { desc = "Horizontal scroll: View right (half screen)" })
vim.keymap.set("n", "<Esc>", "<Cmd>nohlsearch<CR>", { desc = "Clear search highlights" })
vim.keymap.set("v", "<", "<gv", { desc = "Visual: Dedent and reselect" })
vim.keymap.set("v", ">", ">gv", { desc = "Visual: Indent and reselect" })

vim.keymap.set({ "n", "v" }, "<leader>.", vim.lsp.buf.code_action, { desc = "LSP: Show code actions" })
vim.keymap.set("n", "<F2>", vim.lsp.buf.rename, { desc = "LSP: Rename symbol under cursor" })
vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, { desc = "LSP: Show code actions" })
vim.keymap.set("n", "<leader>cd", vim.diagnostic.open_float, { desc = "Diagnostics: Show under cursor" })
vim.keymap.set("n", "<leader>cr", vim.lsp.buf.rename, { desc = "LSP: Rename symbol under cursor" })

vim.keymap.set({ 'n', 'x' }, 's', '<Nop>', { desc = "Disable 's' (substitute character)" })
